"    # comment to end of line!Hash can be used in REED files, and is also used in this syntax summary\n"
"\n"
"    ### syntax notation...\n"
"\n"
"    x ::= y # define non-terminal x to be y\n"
"    x | y   # x or y\n"
"    {x}     # bracket in syntax definitions\n"
"    x+      # at least one x\n"
"    x++     # at least one x, separated by spaces\n"
"    [x]     # optional x\n"
"            # spaces/blanks can be put between all syntactic items and used freely for layout \n"
"\n"
"    ### REED syntax...\n"
"\n"
"    id ::= {letter | digit | underline}+ | string\n"
"    string ::= \"C string, \\n for newline etc\" | <<< terminator\n                                                        arbitrary-string\n                                                terminator\n"
"\n"
"    # reserved words cannot be used as ids unless written inside strings\n"
"    # id xyz and string \"xyz\" are equivalent\n"
"    # the string notation just allows more characters\n"
"\n"
"    ### the following are definitions of non-terminals\n"
"\n"
"    arrow ::= -> | <- | <->\n"
"    color ::= black | blue | green | red | white | yellow\n"
"    id-or-star ::= id | *\n"
"    node-or-arrow ::= id | id {arrow id}+\n"
"    node-or-arrow-list ::= node-or-arrow | ( node-or-arrow++ )\n"
"\n"
"    ### the following are REED statements\n"
"    ### all terminals below are reserved words\n"
"\n"
"    check id => id!Check there is a path from id1 to id2\n"
"    direction {LR | RL | TB | BT}!Primary direction of graph is left-right, right-left, top-bottom, or bottom-top\n"
"    group node-or-arrow-list is id!The nodes are grouped, and the group is named\n"
"    highlight color [cascade] is id!Explain color as id, optionally cascading when it is used\n"
"    highlight id is color!Highlight node id with color\n"
"    htmldefinitions id!Insert id at start of <body> in HTML file\n"
"    latexdefinitions id!Insert id at start of Latex file\n"
"    new style id is id!Define id1 as a style, using Dot syntax for id2 (e.g., \"fontcolor=blue;fontsize=18\")\n"
"    node-or-arrow [is id]!Create nodes or arrows, with optional name id\n"
"    note node-or-arrow-list [is id [;]] [author id [;]] id!Provide narrative note for the nodes or arrows, optionally naming them\n"
"    numbering ( {( id-or-star+ )}++ )!Make the nodes references row.column numbers following the grid layout\n"
"    [override] {abstract | date | title | version} id!Provide abstract, date, etc. Just once, unless overide\n"
"    ref id is id!Change the reference of node id1 to be id2\n"
"    rows [TOC] ( {id ( id+ )}++ )!Draw a graph with a structured layout, with optional Theory of Change styling\n"
"    style node-or-arrow-list is id!Set style of nodes or arrows, either to explicit Dot style or to a named style\n"
"    tags id id!Only process REED code between id1 (begin) and id2 (end) (so needs id2 to stop REED processing)\n"
"\n"
"    ; # semicolons are empty statements, and can be placed only between statements\n"
"\n"
"    Use Unix command reed (no parameters) to summarise flags\n"
