"    Use reed (no parameters) to summarise flags\n"
"\n"
"    Syntax summary\n"
"    ==============\n"
"\n"
"    # comment to end of line\n"
"    # Hash \"#\" is used in REED files, and is also used for comments in this syntax summary\n"
"\n"
"    ### syntax notation...\n"
"\n"
"    x ::= y # define non-terminal x to be y\n"
"    x | y   # x or y\n"
"    { x }   # grouping in syntax definitions\n"
"    x+      # at least one x. Short for: x | xx | xxx...\n"
"    x++     # at least one x. Short for: x | x x | x x x... separated by blanks (spaces/tabs/newlines)\n"
"    [ x ]   # optional x\n"
"            # spaces/blanks can be put between all syntactic items and used freely for layout \n"
"\n"
"    ### REED syntax...\n"
"\n"
"    id ::= { letter | digit | underline }+ | Cstring | Herestring\n"
"    Cstring ::= \"C string, \\n for newline, \\\\ for backslash etc\" \n"
"    Herestring ::= <<< arbitrary-terminator\n                           characters (no escapes needed) over any number of lines\n                       same arbitrary-terminator at start of line\n"
"\n"
"    ### narrative strings in notes are translated to HTML and Latex, and can include:\n"
"\n"
"    <html> ...        # following text is copied to HTML, but skipped in Latex\n"
"    <latex> ...       # following text is copied to Latex, but skipped in HTML\n"
"    <both> ...        # following text is mixed basic HTML and Latex (use flag -rules to see translation rules)\n"
"    <insert> filename  # insert the text contents of file\n"
"    [[[id]]]!replace with id's name and make a cross-reference link (in both HTML and Latex)\n"
"\n"
"    # reserved words can be used as ids if written as strings\n"
"    # otherwise, id xyz and string \"xyz\" are equivalent\n"
"    # so red is reserved, but \"red\" can be used arbitrarily\n"
"    # string notations allow more characters to be used\n"
"\n"
"    ### the following are definitions of non-terminals\n"
"\n"
"    arrow ::= -> | <- | <->\n"
"    color ::= black | blue | green | red | white | yellow\n"
"    id-list ::= id++\n"
"    id-or-star ::= id | *\n"
"    node-or-arrow ::= id | id { arrow id }+\n"
"    node-or-arrow-list ::= node-or-arrow | ( node-or-arrow++ )\n"
"    document-details ::= abstract | author | date | title\n"
"\n"
"    ### the following are REED statements\n"
"    ### all terminals below are reserved words\n"
"\n"
"    check id1 => id2!Check there is a path from id1 to id2\n"
"    direction { LR | RL | TB | BT }!Primary direction of graph is left-right, right-left, top-bottom, or bottom-top\n"
"    document-details id!Specify document details. author id can be used multiple times for multiple authors\n"
"    group node-or-arrow-list is id!The nodes are grouped, and the group is named\n"
"    highlight color [ cascade ] is id!Explain color as id, optionally cascading when it is used\n"
"    highlight id is color!Highlight node id with color\n"
"    htmldefinitions id!Insert id at start of <body> in HTML file; multiple htmldefinitions append it\n"
"    latexdefinitions id!Insert id at start of Latex file; multiple latexdefinitions append id \n"
"    new style id1 is id2!Define id1 as a style, using Dot syntax for id2!(e.g., new style blue18 is \"fontcolor=blue; fontsize=18\")\n"
"    node-or-arrow [ is id ]!Create nodes or arrows, with optional display name id\n"
"    note id1 [ is id2 ] id3!Basic notes: make id3 the note for id1, and optionally name id1 as id2\n"
"    [ keyword[s] id-list ]+ note node-or-arrow-list [ is id1 [;] ] [ author id2 [;] ] id3!General note forms: name nodes or arrows id1, and provide narrative note id3 for them, optionally with one or more keywords/keyphrases\n"
"    numbering ( { ( id-or-star+ ) }++ )!Make node references row.column numbers following the grid layout\n"
"    ref id1 is id2!Set the reference of node id1 to be id2\n"
"    rows [ TOC ] ( { id ( id+ ) }++ )!Draw a graph with a structured layout, with optional TOC (Theory of Change) styling\n"
"    style node-or-arrow-list is id!Set style of nodes or arrows, either to a named style or to an explicit Dot specification\n"
"    tags id1 id2!Only process REED code between id1 (begin) and id2 (end)\n"
"    version id!Subsequent REED code is version id (see flag v=value)\n"
"\n"
"    ;!semicolons are empty statements, and can be placed freely between statements!... and in note statements for legibility\n"
"    override ...!Permit conflicting commands (e.g., title) to override earlier commands (used with version id and flag v=id)\n"
"\n"
"    # The order of commands does not matter, except for:\n"
"    #   override, tags, and version!which affect all following text\n"
"    #   author, htmldefinitions, and latexdefinitions!which append in REED file order\n"
