"    # comment to end of line\n"
"\n"
"    ### syntax notation...\n"
"\n"
"    x ::= y # define non-terminal x to be y\n"
"    x | y # x or y\n"
"    {x} # bracket in syntax definitions\n"
"    x+ # at least one x\n"
"    x++ # at least one x, separated by spaces\n"
"    [x] # optional x\n"
"\n"
"    ### REED syntax...\n"
"\n"
"    id ::= {letter | digit | underline}+ | string\n"
"    string ::= \"C string\" | <<< terminator\n                            arbitrary-string\n                            terminator\n"
"\n"
"    # reserved words cannot be used as ids unless written inside strings\n"
"    # id xyz and string \"xyz\" are equivalent\n"
"    # the string notation just allows more characters\n"
"\n"
"    ### the following are non-terminals\n"
"    arrow ::= -> | <- | <->\n"
"    color ::= black | blue | green | red | white | yellow\n"
"    id-or-star ::= id | *\n"
"    node-or-arrow ::= id | id {arrow id}+\n"
"    node-or-arrow-list ::= node-or-arrow | ( node-or-arrow++ )\n"
"\n"
"    ### all terminals below are reserved words\n"
"    ### the following are REED statements\n"
"\n"
"    check id => id\n"
"    direction {LR | RL | TB | BT}\n"
"    group node-or-arrow-list is id\n"
"    highlight color [cascade] is id\n"
"    highlight id is color\n"
"    htmldefinitions id\n"
"    latexdefinitions id\n"
"    new style id is id\n"
"    node-or-arrow [is id]\n"
"    note node-or-arrow-list [is id [;]] [author id [;]] id\n"
"    numbering ( {( id-or-star+ )}++ )\n"
"    [override] {abstract | date | title | version} id\n"
"    ref id is id\n"
"    rows [TOC] ( {id ( id+ )}++ )\n"
"    style node-or-arrow-list is id\n"
"    tags id id\n"
"    ; # semicolons are empty statements, and can be placed only between statements\n"
"\n"
"    Use Unix command reed (no parameters) to summarise flags\n"
