{title: "Princess of Wales Hospital blood glucometer case REED",
 version: "v3",
 authors: ["Harold Thimbleby"],
 date: "26 January 2025",
 abstract: "\\noindent Example automatically-generated evidence narrative file revisiting the 2014 Princess of Wales Hospital blood glucometer case. For an overview of the background to the case, with a full description of the meaning of the diagram and further details of its associated narrative, go to the web site home page at: \\\\ \\\\ \\hbox to \\textwidth{\\hfill\\textcolor{blue}{\\url{https://harold.thimbleby.net/reeds}}\\hfill} \\\\ \\\\\n\nNode numbers in this narrative evidence document refer to the REED diagram shown on page \\pageref{thefigure} of this document.\n\n\\setbox0=\\hbox{\\textcolor{blue}{\\url{https://harold.thimbleby.net/reeds/REED.pdf}}}\n\n\\begin{figure}\\includegraphics[width=\\textwidth]{../REED-paper/figures/reedv3.pdf}\\\\\n\\sf For convenience, this is a copy of figure \\ref{fig:v3} from page \\pageref{fig:v3} of the REED paper itself,\\\\ \\copy0\n\\label{thefigure}\n\\end{figure}\\newpage",
 styles:
 [ {"wideBlackArrow": "color=black; penwidth=4"},
   {"thinHuman": "color=black; penwidth=1; arrowhead=dot"},
   {"thickDashedBlue": "label="?",fontname="Helvetica-Bold",fontcolor=blue,fontsize=18; penwidth=2; style=dashed"},
   {"thickDashedRed": "label="?",fontname="Helvetica-Bold",fontcolor=red,fontsize=18; color=red; penwidth=2; style=dashed"},
   {"thickHumanDashedRed": "label="?",fontname="Helvetica-Bold",fontcolor=red,fontsize=18; color=red; penwidth=2; style=dashed; arrowhead=dot"},
   {"thickHuman": "color=black; penwidth=2; arrowhead=dot"}
 ],
 "flagstyle": "fillcolor=%s; style=filled; penwidth=2; shape=note; ",
nodes:
[
 {id: "engineer", rankx: 0, ranky: 0,
  is: "Unsupervised\nAbbott\nengineer",
  notes: "\t\\warn{An Abbott engineer, Mr.\\ Reece, had been asked to help when the Princess of Wales PrecisionWeb database faced problems in 2013. Mr.\\ Reece then worked unsupervised on the PrecisionWeb database.}\n\t\n\t\\warn{Reece gave evidence that he had failed to take notes on exactly what he did when editing, deleting, and modifying data in the PrecisionWeb database. He admitted he had deleted critical data, which would have created the impression that nurses had been negligent not performing blood glucose tests.}\n\t\n\t\\warn{This deletion of computer evidence explains the discrepancy in patient records that the prosecution claims had been wholly and entirely caused by the nurses' criminal negligence.}",
  highlight: "blue",
  group: "",
  styleName: "",
  style: "",
 }, 
 {id: "1", rankx: 1, ranky: 1,
  is: "Defendant\nnurses\non Ward 2",
  notes: "\tThe defendants were named, and provided witness statements.",
  highlight: "none",
  group: "",
  styleName: "",
  style: "",
 }, 
 {id: "2", rankx: 1, ranky: 2,
  is: "Patients",
  notes: "\tThe patients on Ward 2 had limited capacity.",
  highlight: "white",
  group: "",
  styleName: "",
  style: "",
 }, 
 {id: "13", rankx: 1, ranky: 3,
  is: "Hospital\ncomputer\noperators",
  notes: "\t\\warn{We have no idea what the hospital computer system operators did, how they were managed, or what their security protocols (if any) were.}\n\n\tNote how (using Statechart\\footnote{Statecharts, invented by David Harel, are well-known diagrams widely used in computer science.} conventions for diagrams) a \\emph{single\\/} arrow from node <<13>>) to the group <<hospital>> is sufficient to show that computer operators affect \\emph{all\\/} nodes inside the box.",
  highlight: "white",
  group: "",
  styleName: "",
  style: "",
 }, 
 {id: "16", rankx: 1, ranky: 4,
  is: "Wrong XceedPros\nseized by police",
  notes: "\tThe PrecisionWeb data records XceedPro serial numbers, and shows that XceedPros routinely move around the hospital. \n\t\n\t\\warn{The PrecisionWeb data confirms that the police seized all three XceedPros that happened to be on Ward 2 on the date when they visited it. However, these were not any XceedPros that had been used by the defendants.} \n\t\n\t\\warn{Seizing the wrong XceedPros will give the false impression that the XceedPro data  confirms the Prosecution's contention that the nurses's fabricated meter readings. The seized XceedPros were checked as reliable by Abbott (node <<17>>) --- that is, Abbott unsurprisingly confirms their XceedPros work as they expect, not that they checked the \\emph{right\\/} XceedPros.}\n\n\tReference \\cite{POW} explains how the police came to seize the wrong XceedPros.",
  highlight: "yellow",
  group: "",
  styleName: "",
  style: "",
 }, 
 {id: "4", rankx: 2, ranky: 1,
  is: "XceedPros\non Ward 2",
  notes: "\tThe nurse takes an XceedPro to a patient, and they must then tap the XceedPro with their ID card, then scan the patient's ID card. Then the patient is pricked to obtain a small blood sample, which is inserted into the XceedPro. The XceedPro records the IDs, the date and time, and the blood glucose level. Nurses may share ID cards, or they may ``double tap'' and use their ID card twice instead of using the patient's ID card. \n\t\n\tSee node <<17>>: \\warn{Manufacturer evidence says XceedPros have numerous bugs; however none of the documented bugs lose patient data.}",
  highlight: "white",
  group: "hospital",
  styleName: "",
  style: "",
 }, 
 {id: "17", rankx: 2, ranky: 2,
  is: "Abbott\nlabs",
  notes: "\tThe US company Abbott manufactured the XceedPros and the PrecisionWeb database, both critical components of this case.\n\n\tThe police sent the wrong 3 XceedPros to Abbott to determine if they worked correctly. The Abbott labs found no relevant problems with the XceedPros, but they did confirm that all XceedPros had bugs.\n\n\tHowever, none of the bugs Abbott described would affect or cause loss of data, unless the XceedPros had been used to try to record over 2,500 tests, which is considerably higher than any XceedPro at the Princess of Wales had ever recorded (at least as established by the police's PrecisionWeb evidence).",
  highlight: "none",
  group: "",
  styleName: "",
  style: "",
 }, 
 {id: "manual", rankx: 3, ranky: 1,
  is: "PrecisionWeb\noperators\nmanual",
  notes: "\t\\warn{The operators manual for PrecisionWeb says it should not be used for clinical purposes. All the evidence for this case assumed the clinical records in PrecisionWeb were reliable.}",
  highlight: "none",
  group: "",
  styleName: "",
  style: "",
 }, 
 {id: "5", rankx: 3, ranky: 2,
  is: "XceedPro\ndock\non ward",
  notes: "\t\\warn{No evidence of the reliability of the XceedPro dock (for example, hospital test results, or manufacturer claims of reliability, or even daily checks of integrity) has been offered. Its reliable use depends on hospital network reliability, and no evidence of the reliability of the hospital network has been offered. The network may have had outages during the relevant period.}",
  highlight: "white",
  group: "hospital",
  styleName: "",
  style: "",
 }, 
 {id: "14", rankx: 3, ranky: 3,
  is: "No evidence\nof any testing\never performed",
  notes: "\t\\warn{The hospital presented no evidence that it knew that any of its systems were reliable. However, the hospital did present evidence that PrecisionWeb regularly crashes (node <<10>>).}",
  highlight: "yellow",
  group: "",
  styleName: "",
  style: "",
 }, 
 {id: "18", rankx: 3, ranky: 4,
  is: "Police summary\nof wrong XceedPros",
  notes: "\t\\warn{Because of the problems noted under node <<16>>, this evidence was excluded.}",
  highlight: "yellow",
  group: "",
  styleName: "",
  style: "",
 }, 
 {id: "7", rankx: 4, ranky: 1,
  is: "Abbott\nPrecisionWeb\ndatabase",
  notes: "\tPrecisionWeb is a proprietary database designed to monitor XceedPros, such as their battery health. \n\t\n\tPrecisionWeb manual warns that it is not designed for clinical use, but the Princess of Wales hospital used it clinically --- the blood glucose readings (amongst other data) are copied, via middleware (node <<8>>) to the main hospital database. \\warn{It is therefore not clear that PrecisionWeb is reliable enough to present patient data as evidence.}",
  highlight: "blue",
  group: "hospital",
  styleName: "",
  style: "",
 }, 
 {id: "6", rankx: 4, ranky: 2,
  is: "Ward PCs",
  notes: "\tThe ward has PCs where nurses can review patient information. \n\t\n\t\\warn{It is not clear whether nurses can edit data, for instance in case two patients were mixed up with the XceedPros (e.g., by putting the wrong test strip in or using one with a second patient) --- and if so, whether edits must be done by the nurse (or person with the same ID) who originally took the readings.}\n\t\n\t\\warn{We do not know who had access to the Ward PCs (whether nurses or hospital operators).}",
  highlight: "blue",
  group: "hospital",
  styleName: "",
  style: "",
 }, 
 {id: "15", rankx: 4, ranky: 3,
  is: "No evidence of\nerror logs\nor audits",
  notes: "\t\\warn{It is astonishing there is no evidence that the hospital ever checked whether their computer systems were functioning normally.}\n\n\t\\warn{It is also astonishing the police recorded data from hospital systems without confirming the reliability of the data, and did so without hospital supervision.}",
  highlight: "yellow",
  group: "",
  styleName: "",
  style: "",
 }, 
 {id: "11", rankx: 5, ranky: 1,
  is: "Police forensic\ndatabase system",
  notes: "\t\\warn{The police used PrecisionWeb unsupervised,\\footnote{Hospital policy has since been revised.} exported data to CSV format.}\n\n\tThe police certainly examined the PrecisionWeb data in Excel, as their written evidence says their first attempts crashed Excel (presumably because of the size of the Excel spreadsheet). I do not understand why the police did not use SQL (or any other decent database), as they could simply have copied the SQL PrecisionWeb database rather than relying on PrecisionWeb to convert it to CSV\\@.\n\n\t\\warn{CSV is a \\textbf{very} unsuitable data format to choose for evidence, as there is no way to detect edited, deleted, or inserted data.}\n\n\tWhatever CSV data they selected, they copied to a USB stick. This stick was then taken by car to a police forensic environment, and copied to an encrypted secure disk drive. Subsequently, unencrypted CDs were burned from the files on the secure disc.\n\n\tThe police evidence claimed their process was forensic --- but it was only forensic \\emph{after\\/} copying CSV data to the secure disk drive, and provided that no police staff with password access modified the data.",
  highlight: "blue",
  group: "",
  styleName: "",
  style: "",
 }, 
 {id: "backups", rankx: 5, ranky: 2,
  is: "No known backups\nthat could have\n provided evidence",
  notes: "\tIf backups had been taken (we do not know) then it would have been\n\tnatural to check the alleged missing nurse data had never been stored\n\ton the main PrecisionWeb database.\n\n\tBackups would have shown whether failures happened in PrecisionWeb, or earlier\n\tfor instance over arrows D, C, B, or A (as the prosecution argued).",
  highlight: "blue",
  group: "",
  styleName: "",
  style: "",
 }, 
 {id: "10", rankx: 5, ranky: 3,
  is: "Frequent crashes\ndocumented",
  notes: "\t\\warn{Evidence revealed in court was that the PrecisionWeb database (or the server it ran on) frequently crashed. The evidence said nothing about the impact of crashes on the integrity of the database; presumably at least the transactions pending when crashes happened would be lost.}",
  highlight: "blue",
  group: "",
  styleName: "",
  style: "",
 }, 
 {id: "8", rankx: 5, ranky: 4,
  is: "Lots of unknown\ncomplex middleware",
  notes: "\tPrecisionWeb (node <<7>>) is not interoperable with other hospital systems, so middleware Conworx is used to interface PrecisionWeb to the main patient databases.\n\t\n\t\\warn{No evidence of the reliability of Conworx and other middleware (for example, hospital test results, or manufacturer claims of reliability) has been mentioned in evidence.}\n\t\n\t\\warn{The hospital refused access to technicians, which meant we have no idea of or the extent of the middleware or how it is supposed to work.}\n\t\n\t\\warn{Such complex multi-manufacturer systems will have bugs, so it is very surprising not to have error logs (etc) presented in routine statements.}",
  highlight: "blue",
  group: "hospital",
  styleName: "",
  style: "",
 }, 
 {id: "12", rankx: 6, ranky: 1,
  is: "Main police evidence",
  notes: "\t\\warn{A joint prosecution/defence expert witness report (``Experts' Joint Statement on Matters Agreed and/or Disagreed in regard to Part 35 12 (3) CPR'') lists many problems, including that the CDs CH/15 the police provided to the prosecution and defence experts were different, raising serious questions of police forensic process \\cite{POW-resources}.}\n\nRefer to node <<11>>. \n%END -- used to help Awk stop copying this note!",
  highlight: "blue",
  group: "",
  styleName: "",
  style: "",
 }, 
 {id: "9", rankx: 6, ranky: 2,
  is: "Main hospital\ndatabases",
  notes: "\tThe hospital databases are managed by hospital technicians. None provided evidence statements, and none were called to give evidence.\n\n\t\\warn{Such complex systems will have bugs, so it is very surprising not to have error logs (etc) presented in routine statements.}\n\n\t\\warn{It is curious that the discrepancies were originally discovered from the main hospital databases, not from PrecisionWeb. The police never took evidence from the main hospital databases.}",
  highlight: "blue",
  group: "hospital",
  styleName: "",
  style: "",
 }, 
 {id: "hospital", rankx: 7, ranky: 1,
  is: "Hospital IT Systems",
  notes: "\t\\warn{We know nothing about the management of the hospital systems and any impact on the evidence.} \\warn{In a hospital (or any other critical environment) one would expect at least daily checks of reliable performance or error logs. The REED diagram shows there were no such checks.}",
  highlight: "none",
  group: "",
  styleName: "",
  style: "",
 }, 
 {id: "3", rankx: 8, ranky: 1,
  is: "Nurse-written\npaper records\n(never disclosed)",
  notes: "\tContemporaneously with treating patients, nurses should review the XceedPro they have used and copy its data to paper notes. The police never provided the nurse-written records. \n\n\t\\warn{The XceedPro can record up to 2,500 patient records and then it will start overwriting records. As I never had access to the relevant XceedPros, I do not know whether this bug was relevant: had an XceedPro recorded about 2,500 records it \\emph{could\\/} have given the impression the nurse had not performed tests the nurse had documented on paper notes.}",
  highlight: "blue",
  group: "",
  styleName: "",
  style: "",
 }, 
],
 arcs: [
  {u: "engineer", v: "7", bidirectional: 0},
  {u: "manual", v: "7", bidirectional: 0},
  {u: "backups", v: "9", bidirectional: 1},
  {u: "7", v: "backups", bidirectional: 1},
  {u: "9", v: "3", bidirectional: 1},
  {u: "8", v: "9", bidirectional: 1},
  {u: "7", v: "8", bidirectional: 1},
  {u: "5", v: "7", bidirectional: 0},
  {u: "4", v: "5", bidirectional: 0},
  {u: "17", v: "18", bidirectional: 0},
  {u: "16", v: "17", bidirectional: 0},
  {u: "16", v: "18", bidirectional: 0},
  {u: "14", v: "15", bidirectional: 0},
  {u: "hospital", v: "14", bidirectional: 0},
  {u: "13", v: "hospital", bidirectional: 0},
  {u: "13", v: "14", bidirectional: 0},
  {u: "11", v: "12", bidirectional: 0},
  {u: "7", v: "11", bidirectional: 0},
  {u: "7", v: "10", bidirectional: 0},
  {u: "6", v: "8", bidirectional: 1},
  {u: "1", v: "6", bidirectional: 0},
  {u: "2", v: "4", bidirectional: 0},
  {u: "1", v: "4", bidirectional: 0},
  {u: "1", v: "3", bidirectional: 0}
],
 groups: [
 {id: "hospital"}
]
}
